//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearcherLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearcherLibrary.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing entry.
        /// </summary>
        internal static string ErrorAccessingEntry {
            get {
                return ResourceManager.GetString("ErrorAccessingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing file.
        /// </summary>
        internal static string ErrorAccessingFile {
            get {
                return ResourceManager.GetString("ErrorAccessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is either corrupt or open in another application..
        /// </summary>
        internal static string FileCorruptOrLockedByApp {
            get {
                return ResourceManager.GetString("FileCorruptOrLockedByApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is either corrupt or protected..
        /// </summary>
        internal static string FileCorruptOrProtected {
            get {
                return ResourceManager.GetString("FileCorruptOrProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file may be encrypted..
        /// </summary>
        internal static string FileEncrypted {
            get {
                return ResourceManager.GetString("FileEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic link file cannot be extracted..
        /// </summary>
        internal static string FileIsSymbolicLink {
            get {
                return ResourceManager.GetString("FileIsSymbolicLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in archive.
        /// </summary>
        internal static string InArchive {
            get {
                return ResourceManager.GetString("InArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex failures - Search cancelled. Correct regular expression and retry. If using Regex, try escaping using the &quot;\&quot; character..
        /// </summary>
        internal static string RegexFailureSearchCancelled {
            get {
                return ResourceManager.GetString("RegexFailureSearchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Not Found.
        /// </summary>
        internal static string SheetNotFound {
            get {
                return ResourceManager.GetString("SheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        internal static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
    }
}
